import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/Providers/Providers";
const geistSans = Geist({ subsets: ['latin'], weight: ['100', '900'] });
const geistMono = Geist({ subsets: ['latin'], weight: ['100', '900'] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="${geistSans.className} bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white">
        <Navbar />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
